import Language from "@/components/Layout/Language";
import Navbar from "@/components/Layout/Navbar";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "CodeForge | LocalLayout",
  description: "Generated by create next app",
};


type Params = Promise<{ locale: string }>;

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  let messages;
  try {
    messages = (await import(`@/messages/${locale}`)).default;
  } catch {
    notFound();
  }
  return (
    <>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Language />
        <Navbar />
        {children}
        <Footer />
      </NextIntlClientProvider>
    </>
  );
}
